// Code generated by "stringer -type=ErrorCategory"; DO NOT EDIT.

package base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownErrorCategory-0]
	_ = x[ErrValidation-1]
	_ = x[ErrConnection-2]
	_ = x[ErrQueueFull-3]
	_ = x[ErrTimeout-4]
}

const _ErrorCategory_name = "UnknownErrorCategoryErrValidationErrConnectionErrQueueFullErrTimeout"

var _ErrorCategory_index = [...]uint8{0, 20, 33, 46, 58, 68}

func (i ErrorCategory) String() string {
	if i >= ErrorCategory(len(_ErrorCategory_index)-1) {
		return "ErrorCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorCategory_name[_ErrorCategory_index[i]:_ErrorCategory_index[i+1]]
}
